//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PreyPreadtor
{
	using System;
	using System.Collections.Generic;
	using System.Drawing;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// трава
	/// </summary>
	public sealed class Grass : Agent
	{

        public Grass(Environment environment, int satiety): base(environment, satiety, Color.Green)
        {
        }

		public void Behaviour()
		{
            //рост травы
            if ((environment.timer % 20) == 0)
                satiety += 1;

            //полупрозрачность травы в зависимости от сытости
            int alpha=(int)(255d*(((double)satiety)/15d));
            if(alpha>255) alpha=255;
            color = Color.FromArgb(alpha, Color.Green);
		}

	}
}

